#!/bin/bash

export PENTAHO_HOME=/opt/biserver-ce
cd ${PENTAHO_HOME} || exit -1

# Prepare the server to run behind a proxy.
# See http://wiki.bizcubed.com.au/xwiki/bin/view/Pentaho+Tutorial/NGiNX+Reverse+SSL+Proxy+for+Pentaho
if [ "x${PROXY_PORT}" != "x" ]; then
    # Once the proxyPort is defined, do not define it again.
    # Otherwise restarting the container breaks
    if ! grep -q proxyPort ${PENTAHO_HOME}/tomcat/conf/server.xml; then
        sed -i "s/<Connector URIEncoding=\"UTF-8\" port=\"8080\" protocol=\"HTTP\/1.1\"/<Connector URIEncoding=\"UTF-8\" port=\"8080\" protocol=\"HTTP\/1.1\" proxyPort=\"${PROXY_PORT}\" scheme=\"${PROXY_SCHEME}\"/" ${PENTAHO_HOME}/tomcat/conf/server.xml
    fi
fi

# Load updated mysql and log4j driver
rm -f ${PENTAHO_HOME}/tomcat/lib/mysql-connector-java*.jar
rm -f ${PENTAHO_HOME}/tomcat/lib/apache-log4j-extras*.jar
cp -f /usr/local/lib/mysql-connector-java-${MYSQL_CONN_VERSION}-bin.jar ${PENTAHO_HOME}/tomcat/lib
cp -f /usr/local/lib/postgresql-${PGSQL_CONN_VERSION}.jar ${PENTAHO_HOME}/tomcat/lib
cp -f /usr/local/lib/apache-log4j-extras-${LOG4J_EXTRAS_VERSION}.jar ${PENTAHO_HOME}/tomcat/lib

# Create properties files to avoid error messages
mkdir -p /home/pentaho/esapi
mkdir -p /home/pentaho/.kettle
touch /home/pentaho/esapi/ESAPI.properties
touch /home/pentaho/.kettle/kettle.properties
chown -R pentaho:pentaho /home/pentaho
chown -R pentaho:pentaho ${PENTAHO_HOME}

# Make sure hazelcast cache is started
sv start hazelcast || exit 1

# Run pentaho server
cd ${PENTAHO_HOME}
#This does not work when using embedded hiperbase
#exec /sbin/setuser pentaho ${PENTAHO_HOME}/tomcat/bin/startup.sh

# Warning! first time must be run manually, queries for auto-update system
exec /sbin/setuser pentaho ${PENTAHO_HOME}/start-pentaho.sh
