#!/usr/bin/env bash

# Add proxy lines to /etc/nginx/proxy/proxy.conf

export IFS='
'

function proxy {

# Proxy URL
cat >> /etc/nginx/proxy/proxy.conf <<EOF
location /$_PREFIX {
    proxy_http_version         1.1;
    proxy_pass_request_headers on;
    
    # La cabecera HOST no va incluida en el proxy_pass_request_headers,
    # Por lo que he podido comprobar... la meto a mano.
    proxy_set_header Host \$http_host;
    proxy_pass $_URL;
    proxy_redirect off;
    break;
}
EOF

}

function proxy_with_static {

# Proxy URL with static content as fallback
cat >> /etc/nginx/proxy/proxy.conf <<EOF
location @$_PREFIX {
    proxy_http_version         1.1;
    proxy_pass_request_headers on;

    # La cabecera HOST no va incluida en el proxy_pass_request_headers,
    # Por lo que he podido comprobar... la meto a mano.
    proxy_set_header Host \$http_host;
    proxy_pass $_URL;
    proxy_redirect off;
    break;
}

location /$_PREFIX {
    alias $_PATH;
    try_files \$uri \$uri/ @$_PREFIX;
}
EOF

}

mkdir -p /etc/nginx/proxy
rm    -f /etc/nginx/proxy/*
for i in `env | grep PROXY_PREFIX_`; do

    # Get environment variables names and values
    export _NAM=`echo "${i}" | cut -d '=' -f 1`
    export _VAL=`echo "${i}" | cut -d '=' -f 2`

    # xargs to trim whitespaces
    # tr to translate uppercase to lowercase
    export _PREFIX=`echo ${_NAM} | sed 's/PROXY_PREFIX_//' | tr '[:upper:]' '[:lower:]' | xargs`
    export _URL=`echo ${_VAL} | cut -d ";" -f 1 | xargs`
    export _PATH=`echo ${_VAL} | cut -s -d ";" -f 2 | xargs`

    # Show what we are doing...
    echo _PREFIX: $_PREFIX
    echo _URL: $_URL
    echo _PATH: $_PATH

    # Dump proxy config
    if [ "x$_PATH" == "x" ]; then
        proxy
    else
        proxy_with_static
    fi

done
